swagger: "2.0"
info:
  version: "0.0.1"
  title: Car Trading Blockchain
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /car/create:
    # binds a127 app logic to a route
    x-swagger-router-controller: car
    post:
      description: Creates a new car
      # used as the method name of the controller
      operationId: create
      parameters:
        - name: body
          in: body
          description: The name of the car owner
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
